#!/usr/bin/env bash

TMPZIP=/tmp/from_nuget.zip
TMPDIR=/tmp/from_nuget
DEST=libs/
SS_VERSION="3.9.56"

function get_package() {
	local name=$1
	local version=$2
	local dir=$3
	echo "$name $version"
	wget --quiet -O $TMPZIP http://packages.nuget.org/api/v2/package/$name/$version
	unzip -q -o $TMPZIP lib/* -d $TMPDIR

	find $TMPDIR/lib/$dir -type f \( -iname "*.dll" -o -iname "*.xml" \) -exec mv '{}' $DEST \;

	rm $TMPDIR -rf
	rm $TMPZIP
}


get_package "taglib" "2.1.0.0" ""
